import os
from dotenv import load_dotenv

load_dotenv()


GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GROQ_MODEL_NAME = "openai/gpt-oss-20b"

# This mapping is the core of the "data integration challenge"
STATE_TO_SUBDIVISION_MAPPING = {
    "ANDHRA PRADESH": ["COASTAL ANDHRA PRADESH", "RAYALSEEMA", "TELANGANA"],
    "UTTAR PRADESH": ["EAST UTTAR PRADESH", "WEST UTTAR PRADESH"],
    "MADHYA PRADESH": ["WEST MADHYA PRADESH", "EAST MADHYA PRADESH"],
    "MAHARASHTRA": ["VIDARBHA", "MADHYA MAHARASHTRA", "MARATHWADA", "KONKAN & GOA"],
    "WEST BENGAL": ["GANGETIC WEST BENGAL", "SUB HIMALAYAN WEST BENGAL & SIKKIM"],
    "TAMIL NADU": ["TAMIL NADU & PONDICHERRY"],
    "KARNATAKA": ["SOUTH INTERIOR KARNATAKA", "NORTH INTERIOR KARNATAKA", "COASTAL KARNATAKA"],
    "KERALA": ["KERALA"],
    "BIHAR": ["BIHAR"],
    "PUNJAB": ["PUNJAB"],
    "RAJASTHAN": ["WEST RAJASTHAN", "EAST RAJASTHAN"],
}